// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qrvczejqxstrwdtpzqxp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFydmN6ZWpxeHN0cndkdHB6cXhwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE1Mjg3MDcsImV4cCI6MjA1NzEwNDcwN30._PT8rKpdipwfr2jcNn0QkMp5WIvYb9pkarvP2j-SPeQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);